name = "dots-3d-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[env.dev]
name = "dots-3d-api-dev"

[[env.dev.durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
